package jantardosfilosofos;

import java.awt.Color;
import java.util.ArrayList;

public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    private MesaDeJantar mesa;
    private ArrayList<Filosofo> listaFilosofo = new ArrayList<Filosofo>(); 
    public InterfaceGrafica() {
        initComponents();
        initializeComponentsStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnStart = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        txtUm = new javax.swing.JTextField();
        txtCinco = new javax.swing.JTextField();
        txtTres = new javax.swing.JTextField();
        txtQuatro = new javax.swing.JTextField();
        txtDois = new javax.swing.JTextField();
        txtGarfoUm = new javax.swing.JTextField();
        txtGarfoDois = new javax.swing.JTextField();
        txtGarfoTres = new javax.swing.JTextField();
        txtGarfoQuatro = new javax.swing.JTextField();
        txtGarfoCinco = new javax.swing.JTextField();
        txtLabelComendo = new javax.swing.JTextField();
        txtLabelPensando = new javax.swing.JTextField();
        txtLabelComFome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLabelOcupado = new javax.swing.JTextField();
        txtLabelLivre = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Início");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnEnd.setText("Fim");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        txtUm.setText("Filosofo 01");
        txtUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmActionPerformed(evt);
            }
        });

        txtCinco.setText("Filosofo 05");
        txtCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCincoActionPerformed(evt);
            }
        });

        txtTres.setText("Filosofo 03");

        txtQuatro.setText("Filosofo 04");

        txtDois.setText("Filosofo 02");

        txtGarfoUm.setText("01");

        txtGarfoDois.setText("02");
        txtGarfoDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarfoDoisActionPerformed(evt);
            }
        });

        txtGarfoTres.setText("03");

        txtGarfoQuatro.setText("04");
        txtGarfoQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarfoQuatroActionPerformed(evt);
            }
        });

        txtGarfoCinco.setText("05");

        txtLabelComendo.setText("COMENDO");

        txtLabelPensando.setText("PENSANDO");

        txtLabelComFome.setText("COM FOME");

        jLabel1.setText("Status - Filosofos");

        jLabel2.setText("Status - Garfos");

        txtLabelOcupado.setText("OCUPADO");

        txtLabelLivre.setText("LIVRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(txtGarfoQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGarfoUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(txtUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(txtGarfoDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(txtGarfoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGarfoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtLabelLivre)
                    .addComponent(txtLabelOcupado)
                    .addComponent(btnStart)
                    .addComponent(btnEnd)
                    .addComponent(txtLabelComendo)
                    .addComponent(txtLabelPensando, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtLabelComFome))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(txtLabelComendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLabelPensando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLabelComFome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLabelOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLabelLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDois, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtGarfoUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGarfoDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGarfoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGarfoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtGarfoQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
		this.mesa = new MesaDeJantar (this);
		Filosofo f = null;
		for (int filosofo = 0; filosofo < 5; filosofo++) {
                    f = new Filosofo("Filosofo_" + filosofo, this.mesa, filosofo);
                    this.listaFilosofo.add(f);
                    f.start();
		}
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        for(int i=0; i<this.listaFilosofo.size(); i++){
            this.listaFilosofo.get(i).setStop(true);
        }
    }//GEN-LAST:event_btnEndActionPerformed

    private void txtUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmActionPerformed

    private void txtCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCincoActionPerformed

    private void txtGarfoDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarfoDoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarfoDoisActionPerformed

    private void txtGarfoQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarfoQuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarfoQuatroActionPerformed

    private void initializeComponentsStatus(){
        this.txtLabelComFome.setBackground(Color.RED);
        this.txtLabelComendo.setBackground(Color.GREEN);
        this.txtLabelPensando.setBackground(Color.GRAY);
        this.txtLabelLivre.setBackground(Color.GRAY);
        this.txtLabelOcupado.setBackground(Color.GREEN);
        this.txtUm.setBackground(Color.GRAY);
        this.txtDois.setBackground(Color.GRAY);
        this.txtTres.setBackground(Color.GRAY);
        this.txtQuatro.setBackground(Color.GRAY);
        this.txtCinco.setBackground(Color.GRAY);
        this.txtGarfoUm.setBackground(Color.GRAY);
        this.txtGarfoDois.setBackground(Color.GRAY);
        this.txtGarfoTres.setBackground(Color.GRAY);
        this.txtGarfoQuatro.setBackground(Color.GRAY);
        this.txtGarfoCinco.setBackground(Color.GRAY);
        
        this.txtUm.setEditable(false);
        this.txtDois.setEditable(false);
        this.txtTres.setEditable(false);
        this.txtQuatro.setEditable(false);
        this.txtCinco.setEditable(false);
        this.txtGarfoUm.setEditable(false);
        this.txtGarfoDois.setEditable(false);
        this.txtGarfoTres.setEditable(false);
        this.txtGarfoQuatro.setEditable(false);
        this.txtGarfoCinco.setEditable(false);
        this.txtLabelComFome.setEditable(false);
        this.txtLabelComendo.setEditable(false);
        this.txtLabelPensando.setEditable(false);
        this.txtLabelLivre.setEditable(false);
        this.txtLabelOcupado.setEditable(false);
    }
    
    private void limparCampoTexto(){
        this.txtCinco.setBackground(Color.GRAY);
        this.txtDois.setBackground(Color.GRAY);
        this.txtQuatro.setBackground(Color.GRAY);
        this.txtTres.setBackground(Color.GRAY);
        this.txtUm.setBackground(Color.GRAY);
    }
    
    private void limparCampoGarfo(){
        this.txtGarfoCinco.setBackground(Color.GRAY);
        this.txtGarfoDois.setBackground(Color.GRAY);
        this.txtGarfoQuatro.setBackground(Color.GRAY);
        this.txtGarfoTres.setBackground(Color.GRAY);
        this.txtGarfoUm.setBackground(Color.GRAY);
    }
       
    private void setComendo(int filosofo){
        if(filosofo==1){
            this.txtUm.setBackground(Color.GREEN);
        }
        else if(filosofo==2){
            this.txtDois.setBackground(Color.GREEN);
        }
        else if(filosofo==3){
            this.txtTres.setBackground(Color.GREEN);
        }
        else if(filosofo==4){
            this.txtQuatro.setBackground(Color.GREEN);
        }
        else if(filosofo==5){
                this.txtCinco.setBackground(Color.GREEN);
        }   
            
    }
    private void setPensando(int filosofo){
        if(filosofo==1) 
            this.txtUm.setBackground(Color.GRAY);
        else if(filosofo==2)
            this.txtDois.setBackground(Color.GRAY);
        else if(filosofo==3)
            this.txtTres.setBackground(Color.GRAY);
        else if(filosofo==4)
            this.txtQuatro.setBackground(Color.GRAY);
        else if(filosofo==5)   
            this.txtCinco.setBackground(Color.GRAY);
    }
    private void setComFome(int filosofo){
        if(filosofo==1) 
            this.txtUm.setBackground(Color.RED);
        else if(filosofo==2)
            this.txtDois.setBackground(Color.RED);
        else if(filosofo==3)
            this.txtTres.setBackground(Color.RED);
        else if(filosofo==4)
            this.txtQuatro.setBackground(Color.RED);
        else if(filosofo==5)   
            this.txtCinco.setBackground(Color.RED);
    }
    private void setOcupado(int garfo){
        if(garfo==1) 
            this.txtGarfoUm.setBackground(Color.GREEN);
        else if(garfo==2)
            this.txtGarfoDois.setBackground(Color.GREEN);
        else if(garfo==3)
            this.txtGarfoTres.setBackground(Color.GREEN);
        else if(garfo==4)
            this.txtGarfoQuatro.setBackground(Color.GREEN);
        else if(garfo==5)   
            this.txtGarfoCinco.setBackground(Color.GREEN);
    }
    private void setLivre(int garfo){
        if(garfo==1) 
            this.txtGarfoUm.setBackground(Color.GRAY);
        else if(garfo==2)
            this.txtGarfoDois.setBackground(Color.GRAY);
        else if(garfo==3)
            this.txtGarfoTres.setBackground(Color.GRAY);
        else if(garfo==4)
            this.txtGarfoQuatro.setBackground(Color.GRAY);
        else if(garfo==5)   
            this.txtGarfoCinco.setBackground(Color.GRAY);
    }
    
    public void SetInterfaceToGarfo(int garfo, String estado){
        if(estado == "LIVRE")
            setLivre(garfo);
        else if(estado == "OCUPADO")
            setOcupado(garfo);
        else
            limparCampoGarfo();
          
        
    }
    
    public void SetInterfaceToFilosofo(int filosofo, String estado){
        if(estado == "COMENDO")
            setComendo(filosofo);
        else if(estado == "COM_FOME")
            setComFome(filosofo);
        else if(estado == "PENSANDO")
            setPensando(filosofo);
        else limparCampoTexto();
        
       //System.out.println(filosofo + "/" + estado);
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
                System.out.println("Teste");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnStart;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtCinco;
    private javax.swing.JTextField txtDois;
    private javax.swing.JTextField txtGarfoCinco;
    private javax.swing.JTextField txtGarfoDois;
    private javax.swing.JTextField txtGarfoQuatro;
    private javax.swing.JTextField txtGarfoTres;
    private javax.swing.JTextField txtGarfoUm;
    private javax.swing.JTextField txtLabelComFome;
    private javax.swing.JTextField txtLabelComendo;
    private javax.swing.JTextField txtLabelLivre;
    private javax.swing.JTextField txtLabelOcupado;
    private javax.swing.JTextField txtLabelPensando;
    private javax.swing.JTextField txtQuatro;
    private javax.swing.JTextField txtTres;
    private javax.swing.JTextField txtUm;
    // End of variables declaration//GEN-END:variables
}
